"""Initial migration

Revision ID: f56fa53a0ce1
Revises: 
Create Date: 2026-07-11 15:21:03.340178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56fa53a0ce1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crime_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('criminals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('aliases', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('repeat_offender', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('risk_score >= 0.0 AND risk_score <= 100.0', name='check_criminal_risk_score'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criminals_repeat_offender'), 'criminals', ['repeat_offender'], unique=False)
    op.create_index(op.f('ix_criminals_risk_score'), 'criminals', ['risk_score'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phones_phone_number'), 'phones', ['phone_number'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_name', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    op.create_table('victims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crime_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_criminal_id', sa.UUID(), nullable=False),
    sa.Column('target_criminal_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='check_relation_confidence_score'),
    sa.ForeignKeyConstraint(['source_criminal_id'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['target_criminal_id'], ['criminals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fir_number', sa.String(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('crime_type_id', sa.UUID(), nullable=False),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.Column('reported_date', sa.Date(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('severity >= 1 AND severity <= 5', name='check_fir_severity'),
    sa.ForeignKeyConstraint(['crime_type_id'], ['crime_types.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fir_district_crime_type', 'firs', ['district_id', 'crime_type_id'], unique=False)
    op.create_index('idx_fir_district_occurrence', 'firs', ['district_id', 'occurrence_date'], unique=False)
    op.create_index('idx_fir_occurrence_crime_type', 'firs', ['occurrence_date', 'crime_type_id'], unique=False)
    op.create_index(op.f('ix_firs_crime_type_id'), 'firs', ['crime_type_id'], unique=False)
    op.create_index(op.f('ix_firs_district_id'), 'firs', ['district_id'], unique=False)
    op.create_index(op.f('ix_firs_fir_number'), 'firs', ['fir_number'], unique=True)
    op.create_index(op.f('ix_firs_latitude'), 'firs', ['latitude'], unique=False)
    op.create_index(op.f('ix_firs_longitude'), 'firs', ['longitude'], unique=False)
    op.create_index(op.f('ix_firs_occurrence_date'), 'firs', ['occurrence_date'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('prediction_type', sa.String(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='check_prediction_confidence'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_prediction_date'), 'predictions', ['prediction_date'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fir_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fir_id'], ['firs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crime_people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fir_id', sa.UUID(), nullable=False),
    sa.Column('criminal_id', sa.UUID(), nullable=True),
    sa.Column('victim_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['fir_id'], ['firs.id'], ),
    sa.ForeignKeyConstraint(['victim_id'], ['victims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crime_people')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_predictions_prediction_date'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_firs_occurrence_date'), table_name='firs')
    op.drop_index(op.f('ix_firs_longitude'), table_name='firs')
    op.drop_index(op.f('ix_firs_latitude'), table_name='firs')
    op.drop_index(op.f('ix_firs_fir_number'), table_name='firs')
    op.drop_index(op.f('ix_firs_district_id'), table_name='firs')
    op.drop_index(op.f('ix_firs_crime_type_id'), table_name='firs')
    op.drop_index('idx_fir_occurrence_crime_type', table_name='firs')
    op.drop_index('idx_fir_district_occurrence', table_name='firs')
    op.drop_index('idx_fir_district_crime_type', table_name='firs')
    op.drop_table('firs')
    op.drop_table('crime_relations')
    op.drop_table('alerts')
    op.drop_table('victims')
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('reports')
    op.drop_index(op.f('ix_phones_phone_number'), table_name='phones')
    op.drop_table('phones')
    op.drop_table('districts')
    op.drop_index(op.f('ix_criminals_risk_score'), table_name='criminals')
    op.drop_index(op.f('ix_criminals_repeat_offender'), table_name='criminals')
    op.drop_table('criminals')
    op.drop_table('crime_types')
    op.drop_table('addresses')
    # ### end Alembic commands ###
